import { MoreHorizontal, ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { study, type Artifact, type ArtifactDetail } from '../../services/study';
import { NotebookClient, notebookRuntime, recordId } from '../../services/notebook';

export function ArtifactView({vaultPath,detail,onRefresh,onRegenerate,onSource,onSetup}:{vaultPath:string;detail:ArtifactDetail;onRefresh:()=>Promise<void>;onRegenerate:()=>void;onSource:(id:string)=>void;onSetup:()=>void}){
 const a=detail.artifact;const [body,setBody]=useState(()=>structuredClone(a.body));const [title,setTitle]=useState(a.title);const [editing,setEditing]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [questionIndex,setQuestionIndex]=useState(0);
 const [filter,setFilter]=useState('');const [sort,setSort]=useState<number|null>(null);const [answers,setAnswers]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);const [cardIndex,setCardIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [practice,setPractice]=useState(false);const [slide,setSlide]=useState(0);const [presenting,setPresenting]=useState(false);const presentation=useRef<HTMLDialogElement>(null);
 const viewer=useRef<HTMLElement>(null);
 useEffect(()=>{viewer.current?.focus({preventScroll:true});},[a.id]);
 const [collapsed,setCollapsed]=useState<string[]>([]);const [zoom,setZoom]=useState(1);const pan=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 useEffect(()=>{setBody(structuredClone(a.body));setTitle(a.title);setEditing(false);setAnswers({});setSubmitted(false);},[a.id,a.version]);
 useEffect(()=>{if(presenting){presentation.current?.showModal();return()=>presentation.current?.close();}},[presenting]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const update=(key:string,index:number,field:string,value:unknown)=>setBody(b=>({...b,[key]:b[key].map((row:any,i:number)=>i===index?{...row,[field]:value}:row)}));
 const refs=(row:any)=><div className="study-citations">{(row.sourceIds??[]).map((id:string)=><button type="button" key={id} onClick={()=>onSource(id)}>{detail.snapshot.sources.find(s=>s.id===id)?.title??id}</button>)}</div>;
 const save=()=>run(async()=>{await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title,body});await onRefresh();});
 const formats:Record<string,string[]>={table:['csv','pdf'],quiz:['md','pdf'],flashcards:['csv','apkg','pdf'],podcast:['mp3','md','pdf'],slides:['pptx','pdf'],mindmap:['svg','md','pdf']};
 const due=body.cards?.filter((c:any)=>{const r=detail.reviews.find(r=>r.cardId===c.id);return !r||r.due<=Date.now()/1000;})??[];const cards=practice?body.cards:due;const card=cards?.[cardIndex%Math.max(cards.length,1)];
 const showSlide=(item:any)=><div className="study-slide"><h2>{item.title}</h2><ul>{item.bullets.map((v:string,i:number)=><li key={i}>{v}</li>)}</ul>{refs(item)}</div>;
 return <section ref={viewer} tabIndex={-1} className="study-artifact" data-kind={a.kind} aria-label="Saved study material" onKeyDown={event=>{if(editing||(event.target as HTMLElement).closest('input,textarea,select,button,summary,dialog'))return;if(a.kind==='flashcards'&&event.key===' '){event.preventDefault();setFlipped(v=>!v);}if(a.kind==='flashcards'&&practice&&(event.key==='ArrowRight'||event.key==='ArrowLeft')){event.preventDefault();setCardIndex(i=>Math.max(0,Math.min(cards.length-1,i+(event.key==='ArrowRight'?1:-1))));setFlipped(false);}if(a.kind==='slides'&&(event.key==='ArrowRight'||event.key==='ArrowLeft')){event.preventDefault();setSlide(i=>Math.max(0,Math.min(body.slides.length-1,i+(event.key==='ArrowRight'?1:-1))));}}}>
  <header className="study-artifact-header"><h2>{a.title}</h2><details className="study-menu"><summary aria-label="Material actions"><MoreHorizontal size={20}/></summary><div className="study-menu-body"><button type="button" disabled={busy} onClick={()=>{setEditing(!editing);setBody(structuredClone(a.body));setTitle(a.title);}}>{editing?'Discard edits':'Edit'}</button><button type="button" disabled={busy||editing} onClick={onRegenerate}>Regenerate as new version</button>{formats[a.kind].map(format=><button type="button" key={format} disabled={busy||editing} onClick={()=>void run(async()=>{const saved=await study.export(vaultPath,a.id,format);setNotice(saved?'Export saved.':'Export cancelled; saved material is unchanged.');})}>Export {format.toUpperCase()}</button>)}</div></details></header>
  <details className="study-material-details"><summary>{detail.snapshot.sources.length} sources · Revision {a.version}{detail.sourcesChanged?' · Sources changed':''}{detail.snapshot.excerpts||body.shortfall?' · Limited coverage':''}</summary><p className="study-muted">Saved locally{detail.snapshot.excerpts?' · selected excerpts, not complete coverage':''}</p>{detail.sourcesChanged&&<p>Sources changed. This material keeps its original source versions.</p>}{body.shortfall&&<p>{body.shortfall}</p>}{detail.snapshot.sources.map(source=><details key={source.id}><summary>{source.path}</summary><pre>{source.text}</pre><button type="button" onClick={()=>onSource(source.id)}>Open current note</button></details>)}</details>
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {editing&&<div className="study-edit-bar"><label className="study-field">Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button type="button" disabled={busy} onClick={()=>void save()}>Save changes</button></div>}
  <div className="study-artifact-body" data-kind={a.kind} data-editing={editing}>
  {a.kind==='table'&&<><label className="study-field">Filter rows<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><div className="study-table"><table><thead><tr>{body.columns.map((column:string,i:number)=><th key={i}>{editing?<input aria-label={`Column ${i+1}`} value={column} onChange={e=>setBody(b=>({...b,columns:b.columns.map((c:string,j:number)=>i===j?e.target.value:c)}))}/>:<button type="button" onClick={()=>setSort(sort===i?null:i)}>{column}{sort===i?' ↑':''}</button>}</th>)}<th>Sources</th></tr></thead><tbody>{body.rows.map((row:any,index:number)=>({row,index})).filter(({row}:any)=>row.cells.join(' ').toLowerCase().includes(filter.toLowerCase())).sort((a:any,b:any)=>sort===null?a.index-b.index:String(a.row.cells[sort]??'').localeCompare(String(b.row.cells[sort]??''),undefined,{numeric:true})).map(({row,index}:any)=><tr key={index}>{row.cells.map((cell:string|null,i:number)=><td key={i}>{editing?<input aria-label={`Row ${index+1} column ${i+1}`} value={cell??''} onChange={e=>update('rows',index,'cells',row.cells.map((c:string,j:number)=>i===j?e.target.value:c))}/>:cell??'Unknown'}</td>)}<td>{refs(row)}</td></tr>)}</tbody></table></div></>}
  {a.kind==='quiz'&&<><form className="study-quiz" onSubmit={e=>{e.preventDefault();void run(async()=>{await study.request(vaultPath,'quizAttempt',{id:a.id,answers:body.questions.map((_:any,i:number)=>answers[i]??null)});setSubmitted(true);await onRefresh();});}}>
   {!editing&&<div className="study-progress"><span>{submitted?'Results':`Question ${questionIndex+1} of ${body.questions.length}`}</span><span>{Object.keys(answers).length} answered</span></div>}
   <div className="study-question-area">{body.questions.map((q:any,i:number)=><fieldset hidden={!editing&&!submitted&&i!==questionIndex} key={q.id??i}><legend>{i+1}. {editing?<input aria-label={`Question ${i+1}`} value={q.question} onChange={e=>update('questions',i,'question',e.target.value)}/>:q.question}</legend>{q.options.map((option:string,j:number)=><label key={j} className="study-choice" data-selected={(editing?q.answer===j:answers[i]===j)}><input type="radio" name={`question-${i}`} disabled={busy||submitted} checked={editing?q.answer===j:answers[i]===j} onChange={()=>editing?update('questions',i,'answer',j):setAnswers(a=>({...a,[i]:j}))}/><span className="study-option-letter">{String.fromCharCode(65+j)}.</span>{editing?<input aria-label={`Question ${i+1} option ${j+1}`} value={option} onChange={e=>update('questions',i,'options',q.options.map((o:string,k:number)=>j===k?e.target.value:o))}/>:<span>{option}</span>}</label>)}{editing?<textarea aria-label={`Explanation ${i+1}`} value={q.explanation} onChange={e=>update('questions',i,'explanation',e.target.value)}/>:submitted&&<p>{answers[i]===q.answer?'Correct.':'Correct answer: '+q.options[q.answer]+'.'} {q.explanation}</p>}{refs(q)}</fieldset>)}</div>
   {!editing&&<footer className="study-player-controls">{!submitted?<><button type="button" disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>i-1)}><ChevronLeft size={16}/> Previous</button>{questionIndex<body.questions.length-1?<button key="next-question" type="button" className="study-primary" onClick={event=>{event.preventDefault();setQuestionIndex(i=>i+1);}}>Next <ChevronRight size={16}/></button>:<button key="score-quiz" type="submit" className="study-primary" disabled={busy}>Score quiz</button>}</>:<><strong>{body.questions.filter((q:any,i:number)=>q.answer===answers[i]).length} / {body.questions.length} correct</strong><button type="button" onClick={()=>{setAnswers({});setSubmitted(false);setQuestionIndex(0);}}>Retry quiz</button></>}</footer>}
   </form>{submitted&&<details><summary>Attempt history</summary>{detail.attempts.map((attempt,i)=><p key={i}>{attempt.score}/{attempt.total} · {new Date(attempt.created*1000).toLocaleString()}</p>)}</details>}</>}
  {a.kind==='flashcards'&&(editing?<div>{body.cards.map((c:any,i:number)=><fieldset key={c.id}><label>Front<textarea value={c.front} onChange={e=>update('cards',i,'front',e.target.value)}/></label><label>Back<textarea value={c.back} onChange={e=>update('cards',i,'back',e.target.value)}/></label>{refs(c)}</fieldset>)}</div>:<div className="study-flashcards"><div className="study-progress"><span>{due.length} due · {body.cards.length} cards</span><label><input type="checkbox" checked={practice} onChange={e=>{setPractice(e.target.checked);setCardIndex(0);setFlipped(false);}}/> Browse all cards</label></div>{card?<><button type="button" className="study-flashcard" aria-label={flipped?'Show question':'Show answer'} onClick={()=>setFlipped(v=>!v)}><span className="study-card-count">{cardIndex%cards.length+1} / {cards.length}</span><span className="study-card-text">{flipped?card.back:card.front}</span><span className="study-card-hint">{flipped?'See question':'See answer'} · Space to flip</span></button>{flipped&&refs(card)}<footer className="study-player-controls">{practice?<><button type="button" aria-label="Previous card" disabled={cardIndex===0} onClick={()=>{setCardIndex(i=>i-1);setFlipped(false);}}><ChevronLeft size={20}/></button><span className="study-muted">Browsing does not change progress</span><button type="button" aria-label="Next card" disabled={cardIndex>=cards.length-1} onClick={()=>{setCardIndex(i=>i+1);setFlipped(false);}}><ChevronRight size={20}/></button></>:flipped?['again','hard','good','easy'].map(rating=><button type="button" key={rating} disabled={busy} onClick={()=>void run(async()=>{await study.request(vaultPath,'review',{id:a.id,cardId:card.id,rating});setFlipped(false);await onRefresh();})}>{rating[0].toUpperCase()+rating.slice(1)}</button>):<span className="study-muted">Flip the card to rate your recall</span>}</footer></>:<div className="study-empty"><RotateCcw size={28}/><h3>No cards due</h3><p>Your progress is saved. Browse all cards to keep practicing.</p></div>}</div>)}
  {a.kind==='slides'&&<>{editing?body.slides.map((s:any,i:number)=><fieldset key={s.id}><input aria-label={`Slide ${i+1} title`} value={s.title} onChange={e=>update('slides',i,'title',e.target.value)}/><textarea aria-label={`Slide ${i+1} bullets`} value={s.bullets.join('\n')} onChange={e=>update('slides',i,'bullets',e.target.value.split('\n'))}/><textarea aria-label={`Slide ${i+1} speaker notes`} value={s.notes} onChange={e=>update('slides',i,'notes',e.target.value)}/><button type="button" disabled={i===0} onClick={()=>setBody(b=>{const slides=[...b.slides];[slides[i-1],slides[i]]=[slides[i],slides[i-1]];return {...b,slides};})}>Move up</button>{refs(s)}</fieldset>):<div className="study-slide-player"><div className="study-slide-stage">{showSlide(body.slides[slide])}</div><details className="study-speaker-notes"><summary>Speaker notes</summary><p>{body.slides[slide].notes}</p></details><div className="study-player-controls"><button type="button" disabled={slide===0} onClick={()=>setSlide(s=>s-1)}>Previous slide</button><span>{slide+1}/{body.slides.length}</span><button type="button" disabled={slide===body.slides.length-1} onClick={()=>setSlide(s=>s+1)}>Next slide</button><button type="button" onClick={()=>setPresenting(true)}>Present</button></div></div>}<dialog ref={presentation} onCancel={()=>setPresenting(false)} className="study-presentation" onKeyDown={e=>{if(e.key==='ArrowRight')setSlide(s=>Math.min(body.slides.length-1,s+1));if(e.key==='ArrowLeft')setSlide(s=>Math.max(0,s-1));}}><button type="button" onClick={()=>setPresenting(false)}>Close presentation</button>{showSlide(body.slides[slide])}<div className="study-toolbar"><button type="button" disabled={slide===0} onClick={()=>setSlide(s=>s-1)}>Previous</button><button type="button" disabled={slide===body.slides.length-1} onClick={()=>setSlide(s=>s+1)}>Next</button></div></dialog></>}
  {a.kind==='mindmap'&&<><div className="study-toolbar"><button type="button" onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>Zoom out</button><button type="button" onClick={()=>setZoom(z=>Math.min(2,z+.1))}>Zoom in</button><button type="button" onClick={()=>{setZoom(1);setCollapsed([]);}}>Reset map</button></div><div ref={pan} className="study-map" onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input,select'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>{drag.current=null;}} onPointerMove={e=>{if(drag.current){e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY;}}}><div style={{transform:`scale(${zoom})`,transformOrigin:'top left',width: `${100/Math.min(1,zoom)}%`}}>{(()=>{const render=(parent:string|null,depth:number):React.ReactNode=>body.nodes.filter((n:any)=>n.parentId===parent).map((n:any)=><div key={n.id} className="study-node" style={{marginLeft:depth*16}}><button type="button" aria-expanded={!collapsed.includes(n.id)} onClick={()=>setCollapsed(c=>c.includes(n.id)?c.filter(id=>id!==n.id):[...c,n.id])}>{collapsed.includes(n.id)?'+':'−'}</button>{editing?<input aria-label={`Node ${n.id}`} value={n.label} onChange={e=>update('nodes',body.nodes.findIndex((x:any)=>x.id===n.id),'label',e.target.value)}/>:<strong>{n.label}</strong>}{refs(n)}{!collapsed.includes(n.id)&&render(n.id,depth+1)}</div>);return render(null,0);})()}</div></div></>}
  {a.kind==='podcast'&&<>{editing?<textarea aria-label="Podcast transcript" value={body.transcript} onChange={e=>setBody(b=>({...b,transcript:e.target.value}))}/>:<><PodcastAudio vaultPath={vaultPath} artifact={a} onRefresh={onRefresh} onSetup={onSetup}/><details><summary>Transcript</summary><p className="study-prewrap">{body.transcript}</p></details></>}</>}
  </div>
 </section>;
}
function PodcastAudio({vaultPath,artifact:a,onRefresh,onSetup}:{vaultPath:string;artifact:Artifact;onRefresh:()=>Promise<void>;onSetup:()=>void}){
 const [client,setClient]=useState<NotebookClient|null>(null);const [profiles,setProfiles]=useState<any[]>([]);const [speakers,setSpeakers]=useState<any[]>([]);const [profile,setProfile]=useState('');const [speaker,setSpeaker]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [url,setUrl]=useState('');
 useEffect(()=>{let alive=true;let object='';void study.request<number[]>(vaultPath,'audio',{id:a.id}).then(bytes=>{if(alive){object=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'audio/mpeg'}));setUrl(object);}}).catch(()=>{});return()=>{alive=false;if(object)URL.revokeObjectURL(object);};},[vaultPath,a.id,a.version]);
 const connect=async()=>{const status=await notebookRuntime.start(vaultPath);if(!status.workspaceId)throw new Error('Notebook runtime unavailable');const c=new NotebookClient(status.workspaceId);setClient(c);const [p,s]=await Promise.all([c.request<any[]>('/episode-profiles'),c.request<any[]>('/speaker-profiles')]);setProfiles(p);setSpeakers(s);return c;};
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const refreshAudio=async()=>{const c=client??await connect();const episodes=await c.request<any[]>('/podcasts/episodes');const episode=episodes.find(e=>e.name===a.body.podcastName);if(!episode)throw new Error('Audio is still processing. Check Jobs, then refresh.');if(episode.error_message)throw new Error(episode.error_message);if(!episode.audio_file&&!episode.audio_url)throw new Error('Audio is still processing. Check Jobs, then refresh.');const blob=await c.media(`/podcasts/episodes/${recordId(episode.id)}/audio`,'audio/mpeg');await study.request(vaultPath,'storeAudio',{id:a.id,bytes:Array.from(new Uint8Array(await blob.arrayBuffer()))});await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title:a.title,body:{...a.body,audioSaved:true,episodeId:episode.id}});await onRefresh();};
 return <div className="study-card">{url&&<audio controls src={url}/>}<p>Five-minute target · uses this artifact’s saved source-grounded script.</p>{error&&<p role="alert">{error}</p>}{!client&&<button type="button" disabled={busy} onClick={()=>void run(async()=>{await connect();})}>Load existing podcast profiles</button>}{client&&<><label>Episode profile<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Choose…</option>{profiles.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label><label>Speaker profile<select value={speaker} onChange={e=>setSpeaker(e.target.value)}><option value="">Choose…</option>{speakers.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label>{(!profiles.length||!speakers.length)&&<p>Configure speech models and profiles in Notebook Manage.</p>}</>}<div className="study-toolbar"><button type="button" disabled={busy||!profile||!speaker||!!a.body.podcastJobId} onClick={()=>void run(async()=>{const c=client??await connect();const name=`${a.title} [${a.id}]`;const result=await c.request<any>('/podcasts/generate','POST',{episode_name:name,episode_profile:profile,speaker_profile:speaker,notebook_id:null,content:a.body.transcript,briefing_suffix:'Target five minutes. Use only this saved script; preserve its facts.'});await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title:a.title,body:{...a.body,podcastJobId:result.job_id,podcastName:name}});await onRefresh();})}>Generate audio</button>{a.body.podcastJobId&&<button type="button" disabled={busy} onClick={()=>void run(refreshAudio)}>Refresh and save audio</button>}<button type="button" onClick={onSetup}>Podcast setup / retry jobs</button></div></div>;
}
