import { useEffect, useRef, useState } from 'react';
import { study, type Artifact, type ArtifactDetail } from '../../services/study';
import { NotebookClient, notebookRuntime, recordId } from '../../services/notebook';

export function ArtifactView({vaultPath,detail,onRefresh,onRegenerate,onSource,onSetup}:{vaultPath:string;detail:ArtifactDetail;onRefresh:()=>Promise<void>;onRegenerate:()=>void;onSource:(id:string)=>void;onSetup:()=>void}){
 const a=detail.artifact;const [body,setBody]=useState(()=>structuredClone(a.body));const [title,setTitle]=useState(a.title);const [editing,setEditing]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [filter,setFilter]=useState('');const [sort,setSort]=useState<number|null>(null);const [answers,setAnswers]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);const [cardIndex,setCardIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [practice,setPractice]=useState(false);const [slide,setSlide]=useState(0);const [presenting,setPresenting]=useState(false);const presentation=useRef<HTMLDialogElement>(null);
 const [collapsed,setCollapsed]=useState<string[]>([]);const [zoom,setZoom]=useState(1);const pan=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 useEffect(()=>{setBody(structuredClone(a.body));setTitle(a.title);setEditing(false);setAnswers({});setSubmitted(false);},[a.id,a.version]);
 useEffect(()=>{if(presenting){presentation.current?.showModal();return()=>presentation.current?.close();}},[presenting]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const update=(key:string,index:number,field:string,value:unknown)=>setBody(b=>({...b,[key]:b[key].map((row:any,i:number)=>i===index?{...row,[field]:value}:row)}));
 const refs=(row:any)=><div className="study-citations">{(row.sourceIds??[]).map((id:string)=><button key={id} onClick={()=>onSource(id)}>{detail.snapshot.sources.find(s=>s.id===id)?.title??id}</button>)}</div>;
 const save=()=>run(async()=>{await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title,body});await onRefresh();});
 const formats:Record<string,string[]>={table:['csv','pdf'],quiz:['md','pdf'],flashcards:['csv','apkg','pdf'],podcast:['mp3','md','pdf'],slides:['pptx','pdf'],mindmap:['svg','md','pdf']};
 const due=body.cards?.filter((c:any)=>{const r=detail.reviews.find(r=>r.cardId===c.id);return !r||r.due<=Date.now()/1000;})??[];const cards=practice?body.cards:due;const card=cards?.[cardIndex%Math.max(cards.length,1)];
 const showSlide=(item:any)=><div className="study-slide"><h2>{item.title}</h2><ul>{item.bullets.map((v:string,i:number)=><li key={i}>{v}</li>)}</ul>{refs(item)}</div>;
 return <section className="study-artifact" aria-label="Saved study material">
  <div className="study-toolbar"><h2>{a.title}</h2><button disabled={busy} onClick={()=>{setEditing(!editing);setBody(structuredClone(a.body));setTitle(a.title);}}> {editing?'Discard edits':'Edit'}</button>{editing&&<button disabled={busy} onClick={()=>void save()}>Save changes</button>}<button disabled={busy||editing} onClick={onRegenerate}>Regenerate as new version</button></div>
  <p className="study-muted">Saved locally · revision {a.version} · {detail.snapshot.sources.length} source notes{detail.snapshot.excerpts?' · selected excerpts, not complete coverage':''}</p>
  {detail.sourcesChanged&&<p role="status">Sources changed. This material keeps its original source versions.</p>}{body.shortfall&&<p role="status">{body.shortfall}</p>}
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {editing&&<label className="study-field">Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label>}
  <div className="study-toolbar" aria-label="Export formats">{formats[a.kind].map(format=><button key={format} disabled={busy||editing} onClick={()=>void run(async()=>{const saved=await study.export(vaultPath,a.id,format);setNotice(saved?'Export saved.':'Export cancelled; saved material is unchanged.');})}>Export {format.toUpperCase()}</button>)}</div>
  {a.kind==='table'&&<><label className="study-field">Filter rows<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><div className="study-table"><table><thead><tr>{body.columns.map((column:string,i:number)=><th key={i}>{editing?<input aria-label={`Column ${i+1}`} value={column} onChange={e=>setBody(b=>({...b,columns:b.columns.map((c:string,j:number)=>i===j?e.target.value:c)}))}/>:<button onClick={()=>setSort(sort===i?null:i)}>{column}{sort===i?' ↑':''}</button>}</th>)}<th>Sources</th></tr></thead><tbody>{body.rows.map((row:any,index:number)=>({row,index})).filter(({row}:any)=>row.cells.join(' ').toLowerCase().includes(filter.toLowerCase())).sort((a:any,b:any)=>sort===null?a.index-b.index:String(a.row.cells[sort]??'').localeCompare(String(b.row.cells[sort]??''),undefined,{numeric:true})).map(({row,index}:any)=><tr key={index}>{row.cells.map((cell:string|null,i:number)=><td key={i}>{editing?<input aria-label={`Row ${index+1} column ${i+1}`} value={cell??''} onChange={e=>update('rows',index,'cells',row.cells.map((c:string,j:number)=>i===j?e.target.value:c))}/>:cell??'Unknown'}</td>)}<td>{refs(row)}</td></tr>)}</tbody></table></div></>}
  {a.kind==='quiz'&&<><form onSubmit={e=>{e.preventDefault();void run(async()=>{await study.request(vaultPath,'quizAttempt',{id:a.id,answers:body.questions.map((_:any,i:number)=>answers[i]??null)});setSubmitted(true);await onRefresh();});}}>{body.questions.map((q:any,i:number)=><fieldset key={q.id??i}><legend>{i+1}. {editing?<input aria-label={`Question ${i+1}`} value={q.question} onChange={e=>update('questions',i,'question',e.target.value)}/>:q.question}</legend>{q.options.map((option:string,j:number)=><label key={j} className="study-choice"><input type="radio" name={`question-${i}`} disabled={busy||submitted} checked={editing?q.answer===j:answers[i]===j} onChange={()=>editing?update('questions',i,'answer',j):setAnswers(a=>({...a,[i]:j}))}/>{editing?<input aria-label={`Question ${i+1} option ${j+1}`} value={option} onChange={e=>update('questions',i,'options',q.options.map((o:string,k:number)=>j===k?e.target.value:o))}/>:option}</label>)}{editing?<textarea aria-label={`Explanation ${i+1}`} value={q.explanation} onChange={e=>update('questions',i,'explanation',e.target.value)}/>:submitted&&<p>{answers[i]===q.answer?'Correct.':'Correct answer: '+q.options[q.answer]+'.'} {q.explanation}</p>}{refs(q)}</fieldset>)}{!editing&&<div className="study-toolbar"><button type="submit" disabled={busy||submitted}>Score quiz</button><button type="button" onClick={()=>{setAnswers({});setSubmitted(false);}}>Retry quiz</button></div>}</form>{detail.attempts.map((attempt,i)=><p key={i}>Attempt: {attempt.score}/{attempt.total} · {new Date(attempt.created*1000).toLocaleString()}</p>)}</>}
  {a.kind==='flashcards'&&(editing?<div>{body.cards.map((c:any,i:number)=><fieldset key={c.id}><label>Front<textarea value={c.front} onChange={e=>update('cards',i,'front',e.target.value)}/></label><label>Back<textarea value={c.back} onChange={e=>update('cards',i,'back',e.target.value)}/></label>{refs(c)}</fieldset>)}</div>:<><p>{due.length} due · {body.cards.length} cards</p><label><input type="checkbox" checked={practice} onChange={e=>{setPractice(e.target.checked);setCardIndex(0);setFlipped(false);}}/> Browse all cards without changing progress</label>{card?<div className="study-card"><p>{flipped?card.back:card.front}</p><button onClick={()=>setFlipped(!flipped)}>Flip card</button>{flipped&&refs(card)}{practice?<button onClick={()=>{setCardIndex(i=>i+1);setFlipped(false);}}>Next card</button>:flipped&&<div className="study-toolbar">{['again','hard','good','easy'].map(rating=><button key={rating} disabled={busy} onClick={()=>void run(async()=>{await study.request(vaultPath,'review',{id:a.id,cardId:card.id,rating});setFlipped(false);await onRefresh();})}>{rating[0].toUpperCase()+rating.slice(1)}</button>)}</div>}</div>:<p>No cards due. Your progress is saved.</p>}</>)}
  {a.kind==='slides'&&<>{editing?body.slides.map((s:any,i:number)=><fieldset key={s.id}><input aria-label={`Slide ${i+1} title`} value={s.title} onChange={e=>update('slides',i,'title',e.target.value)}/><textarea aria-label={`Slide ${i+1} bullets`} value={s.bullets.join('\n')} onChange={e=>update('slides',i,'bullets',e.target.value.split('\n'))}/><textarea aria-label={`Slide ${i+1} speaker notes`} value={s.notes} onChange={e=>update('slides',i,'notes',e.target.value)}/><button disabled={i===0} onClick={()=>setBody(b=>{const slides=[...b.slides];[slides[i-1],slides[i]]=[slides[i],slides[i-1]];return {...b,slides};})}>Move up</button>{refs(s)}</fieldset>):<>{showSlide(body.slides[slide])}<p>Speaker notes: {body.slides[slide].notes}</p><div className="study-toolbar"><button disabled={slide===0} onClick={()=>setSlide(s=>s-1)}>Previous slide</button><span>{slide+1}/{body.slides.length}</span><button disabled={slide===body.slides.length-1} onClick={()=>setSlide(s=>s+1)}>Next slide</button><button onClick={()=>setPresenting(true)}>Present</button></div></>}<dialog ref={presentation} onCancel={()=>setPresenting(false)} className="study-presentation" onKeyDown={e=>{if(e.key==='ArrowRight')setSlide(s=>Math.min(body.slides.length-1,s+1));if(e.key==='ArrowLeft')setSlide(s=>Math.max(0,s-1));}}><button onClick={()=>setPresenting(false)}>Close presentation</button>{showSlide(body.slides[slide])}<div className="study-toolbar"><button disabled={slide===0} onClick={()=>setSlide(s=>s-1)}>Previous</button><button disabled={slide===body.slides.length-1} onClick={()=>setSlide(s=>s+1)}>Next</button></div></dialog></>}
  {a.kind==='mindmap'&&<><div className="study-toolbar"><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>Zoom out</button><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>Zoom in</button><button onClick={()=>{setZoom(1);setCollapsed([]);}}>Reset map</button></div><div ref={pan} className="study-map" onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input,select'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={()=>{drag.current=null;}} onPointerMove={e=>{if(drag.current){e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY;}}}><div style={{transform:`scale(${zoom})`,transformOrigin:'top left',width: `${100/Math.min(1,zoom)}%`}}>{(()=>{const render=(parent:string|null,depth:number):React.ReactNode=>body.nodes.filter((n:any)=>n.parentId===parent).map((n:any)=><div key={n.id} className="study-node" style={{marginLeft:depth*16}}><button aria-expanded={!collapsed.includes(n.id)} onClick={()=>setCollapsed(c=>c.includes(n.id)?c.filter(id=>id!==n.id):[...c,n.id])}>{collapsed.includes(n.id)?'+':'−'}</button>{editing?<input aria-label={`Node ${n.id}`} value={n.label} onChange={e=>update('nodes',body.nodes.findIndex((x:any)=>x.id===n.id),'label',e.target.value)}/>:<strong>{n.label}</strong>}{refs(n)}{!collapsed.includes(n.id)&&render(n.id,depth+1)}</div>);return render(null,0);})()}</div></div></>}
  {a.kind==='podcast'&&<>{editing?<textarea aria-label="Podcast transcript" value={body.transcript} onChange={e=>setBody(b=>({...b,transcript:e.target.value}))}/>:<><PodcastAudio vaultPath={vaultPath} artifact={a} onRefresh={onRefresh} onSetup={onSetup}/><details><summary>Transcript</summary><p className="study-prewrap">{body.transcript}</p></details></>}</>}
  <details><summary>Original source versions</summary>{detail.snapshot.sources.map(s=><details key={s.id}><summary>{s.path} · {s.hash}</summary><pre>{s.text}</pre><button onClick={()=>onSource(s.id)}>Open current note</button></details>)}</details>
 </section>;
}
function PodcastAudio({vaultPath,artifact:a,onRefresh,onSetup}:{vaultPath:string;artifact:Artifact;onRefresh:()=>Promise<void>;onSetup:()=>void}){
 const [client,setClient]=useState<NotebookClient|null>(null);const [profiles,setProfiles]=useState<any[]>([]);const [speakers,setSpeakers]=useState<any[]>([]);const [profile,setProfile]=useState('');const [speaker,setSpeaker]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [url,setUrl]=useState('');
 useEffect(()=>{let alive=true;let object='';void study.request<number[]>(vaultPath,'audio',{id:a.id}).then(bytes=>{if(alive){object=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'audio/mpeg'}));setUrl(object);}}).catch(()=>{});return()=>{alive=false;if(object)URL.revokeObjectURL(object);};},[vaultPath,a.id,a.version]);
 const connect=async()=>{const status=await notebookRuntime.start(vaultPath);if(!status.workspaceId)throw new Error('Notebook runtime unavailable');const c=new NotebookClient(status.workspaceId);setClient(c);const [p,s]=await Promise.all([c.request<any[]>('/episode-profiles'),c.request<any[]>('/speaker-profiles')]);setProfiles(p);setSpeakers(s);return c;};
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const refreshAudio=async()=>{const c=client??await connect();const episodes=await c.request<any[]>('/podcasts/episodes');const episode=episodes.find(e=>e.name===a.body.podcastName);if(!episode)throw new Error('Audio is still processing. Check Jobs, then refresh.');if(episode.error_message)throw new Error(episode.error_message);if(!episode.audio_file&&!episode.audio_url)throw new Error('Audio is still processing. Check Jobs, then refresh.');const blob=await c.media(`/podcasts/episodes/${recordId(episode.id)}/audio`,'audio/mpeg');await study.request(vaultPath,'storeAudio',{id:a.id,bytes:Array.from(new Uint8Array(await blob.arrayBuffer()))});await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title:a.title,body:{...a.body,audioSaved:true,episodeId:episode.id}});await onRefresh();};
 return <div className="study-card">{url&&<audio controls src={url}/>}<p>Five-minute target · uses this artifact’s saved source-grounded script.</p>{error&&<p role="alert">{error}</p>}{!client&&<button disabled={busy} onClick={()=>void run(async()=>{await connect();})}>Load existing podcast profiles</button>}{client&&<><label>Episode profile<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Choose…</option>{profiles.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label><label>Speaker profile<select value={speaker} onChange={e=>setSpeaker(e.target.value)}><option value="">Choose…</option>{speakers.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select></label>{(!profiles.length||!speakers.length)&&<p>Configure speech models and profiles in Notebook Manage.</p>}</>}<div className="study-toolbar"><button disabled={busy||!profile||!speaker||!!a.body.podcastJobId} onClick={()=>void run(async()=>{const c=client??await connect();const name=`${a.title} [${a.id}]`;const result=await c.request<any>('/podcasts/generate','POST',{episode_name:name,episode_profile:profile,speaker_profile:speaker,notebook_id:null,content:a.body.transcript,briefing_suffix:'Target five minutes. Use only this saved script; preserve its facts.'});await study.request(vaultPath,'saveArtifact',{id:a.id,version:a.version,title:a.title,body:{...a.body,podcastJobId:result.job_id,podcastName:name}});await onRefresh();})}>Generate audio</button>{a.body.podcastJobId&&<button disabled={busy} onClick={()=>void run(refreshAudio)}>Refresh and save audio</button>}<button onClick={onSetup}>Podcast setup / retry jobs</button></div></div>;
}
