import { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { knowledge, type ChatLibrarySession } from '../../services/knowledge';
import { sharedStudy, study, useSharedStudy, type Collection } from '../../services/study';

export function SharedChat({vaultPath,collectionId=null,onOtherView,onOpenSettings}: {vaultPath:string;collectionId?:string|null;onOtherView?:()=>void;onOpenSettings?:()=>void}){
 const shared=useSharedStudy(vaultPath);const id=shared.active;const detail=id?shared.details[id]:null;
 const [input,setInput]=useState('');const [sessions,setSessions]=useState<ChatLibrarySession[]>([]);const [error,setError]=useState('');const [collections,setCollections]=useState<Collection[]>([]);
 const refresh=()=>knowledge.listChats(null,null,200).then(setSessions).catch(e=>setError(String(e)));
 useEffect(()=>{void refresh();void study.request<Collection[]>(vaultPath,'collections').then(setCollections).catch(()=>{});},[vaultPath,id,detail?.messages.length]);
 useEffect(()=>{if(detail?.managed)return;const pending=detail?.messages.some(m=>m.role==='user')??false;if(!pending||!id)return;let active=true;const entry=sessions.find(row=>row.id===id);if(!entry)return;const timer=window.setTimeout(()=>{void study.legacy(vaultPath,entry).then(()=>study.request<boolean>(vaultPath,'isManaged',{id})).then(managed=>{if(active&&managed)void sharedStudy.open(vaultPath,id);}).catch(e=>setError(String(e)));},0);return()=>{active=false;clearTimeout(timer);};},[vaultPath,id,detail?.managed,detail?.messages.length,sessions]);
 const [retryText,setRetryText]=useState('');  const run=async(fn:()=>Promise<unknown>)=>{try{setError('');await fn();await refresh();}catch(e){setError(String(e));}};
 const send=async()=>{if(!input.trim())return;let target=id;if(!target)target=await sharedStudy.create(vaultPath,collectionId);const text=input;setInput('');setRetryText(text);void sharedStudy.send(vaultPath,target,text);};
 const linked=collections.find(c=>c.id===detail?.collectionId);
 return <section className="study-chat" aria-label="Shared conversation">
  <div className="study-toolbar"><select aria-label="Conversation" value={id??''} onChange={e=>{const row=sessions.find(s=>s.id===e.target.value);if(row)void run(async()=>{await study.legacy(vaultPath,row);await sharedStudy.open(vaultPath,row.id);});}}><option value="">Choose a conversation</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><button onClick={()=>void run(()=>sharedStudy.create(vaultPath,collectionId))}>New chat</button>{onOtherView&&<button onClick={onOtherView}>Open in other view</button>}</div>
  {detail&&<><label className="study-field">Conversation title<input aria-label="Conversation title" defaultValue={detail.session.title} key={id} onBlur={e=>{if(e.target.value.trim()&&e.target.value!==detail.session.title)void run(async()=>{await knowledge.renameChat(id!,e.target.value);await sharedStudy.open(vaultPath,id!);});}}/></label><p className="study-muted">{linked?`Sources: ${linked.title} · ${linked.sourceIds.length} selected notes`:'Sources: existing vault retrieval scope'}</p>{collectionId&&detail.collectionId!==collectionId&&<button disabled={shared.running[id!]} onClick={()=>void run(async()=>{await study.request(vaultPath,'adoptChat',{id,collectionId});await sharedStudy.open(vaultPath,id!);})}>Use this collection for future messages</button>}</>}
  {(error||(id&&shared.errors[id]))&&<div role="alert">{error||(id&&shared.errors[id])}<button onClick={onOpenSettings}>AI settings</button></div>}
  <div className="study-messages" aria-live="polite">{!detail&&<p>Select a collection and start a conversation, or continue an existing chat. The same conversation is available in both views.</p>}{detail?.messages.map(m=><article key={m.id}><strong>{m.role==='user'?'You':'Prism'}</strong><ReactMarkdown>{m.content}</ReactMarkdown>{m.metadata&&(()=>{try{const meta=JSON.parse(m.metadata);return meta.excerpts?<small>Uses selected excerpts rather than complete source coverage.</small>:null;}catch{return null;}})()}</article>)}{id&&shared.running[id]&&<article><strong>Prism</strong><ReactMarkdown>{shared.drafts[id]||'Preparing a response…'}</ReactMarkdown></article>}</div>
  <form onSubmit={e=>{e.preventDefault();void run(send);}}><textarea aria-label="Message" placeholder="Ask about your sources…" value={input} onChange={e=>setInput(e.target.value)}/><div className="study-toolbar"><button type="submit" disabled={!input.trim()||!!(id&&shared.running[id])}>Send</button>{id&&shared.running[id]&&<button type="button" onClick={()=>void run(()=>sharedStudy.cancel(vaultPath,id))}>Cancel response</button>}{id&&shared.errors[id]&&<button type="button" onClick={()=>{const last=retryText||detail?.messages.filter(m=>m.role==='user').at(-1)?.content;if(last)void sharedStudy.send(vaultPath,id,last);}}>Retry response</button>}</div></form>
 </section>;
}
