import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { knowledge } from '../../services/knowledge';
import { listen } from '@tauri-apps/api/event';
import { study, sharedStudy, useSharedStudy, STUDY_TOOLS, type Artifact, type ArtifactDetail, type Collection, type StudySource, type ToolKind } from '../../services/study';
import { useDialog } from '../DialogProvider';
import { SharedChat, type ChatModelPicker } from './SharedChat';
import { ArtifactView } from './ArtifactView';
import './study.css';
import '../ui/notebook-tokens.css';
import { NotebookLibrary } from './NotebookLibrary';
import { StudyPanels, type StudyPane } from './StudyPanels';
import { StatusMark, type StatusState } from '../ui/StatusMark';
import { Plus, ArrowLeft, FileText, MoreHorizontal, Table2, ListChecks, Layers, Headphones, Presentation, Network, SlidersHorizontal } from 'lucide-react';
import type { OmniRouteConfig } from '../../types';

/** One study-tool generation run with its own lifecycle status. */
interface GenerationTask { id: string; jobId?:string; progress?:number; collectionId: string; instructions: string; artifactId?: string; kind: ToolKind; parentId: string | null; status: 'preparing' | 'generating' | 'done' | 'failed' | 'cancelled'; error?: string }
const TASK_STATUS: Record<GenerationTask['status'], StatusState> = { preparing: 'pending', generating: 'running', done: 'done', failed: 'failed', cancelled:'cancelled' };

export function StudyWorkspace({vaultPath,onImport,onOpenNote,onOpenSettings,onOtherChatView,onOpenLegacy,legacy,unsavedPaths=[],config,modelPicker,onVaultChanged}:{vaultPath:string;onImport:()=>void;onOpenNote:(path:string)=>void;onOpenSettings:()=>void;onOtherChatView:()=>void;onOpenLegacy?:(section:'workspace'|'transformations'|'podcasts'|'settings')=>void;legacy:ReactNode;unsavedPaths?:string[];config:OmniRouteConfig;modelPicker?:ChatModelPicker;onVaultChanged?:()=>void}){
 const [library,setLibrary]=useState(true);const [allMaterials,setAllMaterials]=useState<Artifact[]>([]);
 const dialogs=useDialog();const shared=useSharedStudy(vaultPath);
 const [collections,setCollections]=useState<Collection[]>([]);const [selected,setSelected]=useState('');const [sources,setSources]=useState<StudySource[]>([]);const [notes,setNotes]=useState<StudySource[]>([]);const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [next,setNext]=useState<number|null>(null);const [pane,setPane]=useState<StudyPane>('chat');const [advanced,setAdvanced]=useState(false);
 const [viewers,setViewers]=useState<Record<string,ArtifactDetail>>({});const [artifactByNotebook,setArtifactByNotebook]=useState<Record<string,string>>({});
 const [artifacts,setArtifacts]=useState<Artifact[]>([]);const [detail,setDetail]=useState<ArtifactDetail|null>(null);const [instructions,setInstructions]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tasks,setTasks]=useState<GenerationTask[]>([]);const cancelled=useRef(new Set<string>());const [preview,setPreview]=useState<StudySource|null>(null);const [newImports,setNewImports]=useState<StudySource[]>([]);
 const [pendingArtifact,setPendingArtifact]=useState('');
 const [revealRevision,setRevealRevision]=useState(0);
 const [adding,setAdding]=useState(false);const [configure,setConfigure]=useState<ToolKind|null>(null);const generationDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(configure){generationDialog.current?.showModal();return()=>generationDialog.current?.close();}},[configure]);
 const alive=useRef(true);const current=useRef(selected);current.current=selected;const operation=useRef(0);const previewOperation=useRef(0);const notesRevision=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;operation.current++;};},[]);
 const active=collections.find(c=>c.id===selected);
 const lastSession=useRef<string|null>(null);useEffect(()=>{const session=shared.active;if(session&&session!==lastSession.current){const linked=shared.details[session]?.collectionId;if(linked){setSelected(linked);setLibrary(false);}lastSession.current=session;}},[shared.active,shared.details]);
 const loadCollections=useCallback(async()=>{const rows=await study.request<Collection[]>(vaultPath,'collections');if(alive.current){setCollections(rows);}},[vaultPath]);
 useEffect(()=>{void study.request<Artifact[]>(vaultPath,'artifacts').then(setAllMaterials).catch(()=>{});void loadCollections().catch(e=>setError(String(e)));},[loadCollections]);
 const loadNotes=useCallback(async()=>{const revision=++notesRevision.current;const page=await study.request<{items:StudySource[];nextOffset:number|null}>(vaultPath,'notes',{query,offset});if(alive.current&&revision===notesRevision.current){setNotes(page.items);setNext(page.nextOffset);}},[vaultPath,query,offset]);
 useEffect(()=>{const timer=setTimeout(()=>void loadNotes().catch(e=>setError(String(e))),180);return()=>clearTimeout(timer);},[loadNotes]);
 const refreshSelection=useCallback(async()=>{if(!selected){setSources([]);setArtifacts([]);return;}const [sourceRows,materials]=await Promise.all([study.request<StudySource[]>(vaultPath,'sources',{collectionId:selected}),study.request<Artifact[]>(vaultPath,'artifacts',{collectionId:selected})]);if(alive.current&&current.current===selected){setSources(sourceRows);setArtifacts(materials);}},[vaultPath,selected]);
 useEffect(()=>{operation.current++;previewOperation.current++;setDetail(viewers[artifactByNotebook[selected]]??null);setPreview(null);setNewImports([]);void refreshSelection().catch(e=>setError(String(e)));},[refreshSelection]);
 useEffect(()=>{const subscription=listen('knowledge-event',()=>{void loadNotes().catch(()=>{});void refreshSelection().catch(()=>{});if(detail)void openArtifact(detail.artifact.id).catch(()=>{});});return()=>{void subscription.then(stop=>stop()).catch(()=>{});};},[loadNotes,refreshSelection,detail?.artifact.id]);
 useEffect(()=>{const handler=(event:Event)=>{const {paths,vault}=(event as CustomEvent<{paths:string[];vault:string}>).detail;if(vault!==vaultPath||!current.current)return;void study.request<StudySource[]>(vaultPath,'importedPaths',{paths}).then(found=>{if(alive.current)setNewImports(found);}).catch(e=>{if(alive.current)setError(String(e));});};window.addEventListener('study-import-published',handler);return()=>window.removeEventListener('study-import-published',handler);},[vaultPath]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setBusy(false);}};
 const saveCollection=async(sourceIds:string[],title=active?.title)=>{if(!active||!title)return;const row=await study.request<Collection>(vaultPath,'saveCollection',{...active,title,sourceIds});if(alive.current){setCollections(rows=>rows.map(c=>c.id===row.id?row:c));await refreshSelection();}};
 const create=()=>run(async()=>{const title=await dialogs.prompt('Notebook name');if(!title?.trim())return;const row=await study.request<Collection>(vaultPath,'saveCollection',{title,sourceIds:[]});await loadCollections();setSelected(row.id);setLibrary(false);});
 const openArtifact=async(id:string)=>{const revision=++operation.current;const d=await study.request<ArtifactDetail>(vaultPath,'artifact',{id});if(alive.current&&revision===operation.current){setDetail(d);setViewers(rows=>({...rows,[d.artifact.id]:d}));setArtifactByNotebook(rows=>({...rows,[d.artifact.collectionId]:d.artifact.id}));setPane('tools');setRevealRevision(r=>r+1);}};
 useEffect(()=>{if(pendingArtifact){void openArtifact(pendingArtifact).catch(e=>setError(String(e)));setPendingArtifact('');}},[pendingArtifact,selected]);
 const generate=async(kind:ToolKind,parentId:string|null=null,origin=selected,prompt=instructions)=>{if(!origin)return;const collectionId=origin;const id=crypto.randomUUID();setTasks(rows=>[...rows,{id,kind,parentId,collectionId,instructions:prompt,status:'preparing'}]);setError('');try{if(!alive.current)return;setTasks(rows=>rows.map(t=>t.id===id?{...t,status:'generating'}:t));const a=await study.generate(vaultPath,collectionId,kind,prompt,parentId,id);if(cancelled.current.has(id))return;if(alive.current){setAllMaterials(rows=>[...rows.filter(row=>row.id!==a.id),a]);if(current.current===collectionId)await refreshSelection();}if(alive.current)setTasks(rows=>rows.map(t=>t.id===id?{...t,status:'done',artifactId:a.id}:t));}catch(e){if(alive.current&&!cancelled.current.has(id)){setError(String(e));setTasks(rows=>rows.map(t=>t.id===id?{...t,status:'failed',error:String(e)}:t));}}};
 useEffect(()=>{const subscription=listen<{vaultPath:string;requestId:string;jobId:string;progress:number}>('study-task-progress',({payload:p})=>{if(p.vaultPath!==vaultPath||!alive.current)return;if(cancelled.current.has(p.requestId)){void knowledge.cancel(p.jobId).catch(()=>{});return;}setTasks(rows=>rows.map(t=>t.id===p.requestId?{...t,jobId:p.jobId,progress:p.progress}:t));});return()=>{void subscription.then(stop=>stop());};},[vaultPath]);
 const cancelTask=async(task:GenerationTask)=>{cancelled.current.add(task.id);setTasks(rows=>rows.map(t=>t.id===task.id?{...t,status:'cancelled'}:t));try{if(task.jobId)await knowledge.cancel(task.jobId);}catch(e){setError(String(e));}};
 const generating=tasks.some(t=>t.status==='preparing'||t.status==='generating');
 const previewSource=async(id:string)=>{const revision=++previewOperation.current;const source=await study.request<StudySource>(vaultPath,'previewSource',{id});if(alive.current&&revision===previewOperation.current){setPreview(source);setPane('sources');setRevealRevision(r=>r+1);}};
 const move=(index:number,delta:number)=>{if(!active)return;const ids=[...active.sourceIds];[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void run(()=>saveCollection(ids));};
 const canGenerate=!!active?.sourceIds.length&&!sources.some(s=>s.missing)&&!generating;
 if(!vaultPath)return <div className="study-workspace"><p>Open a vault to use Notebook.</p></div>;
 const icons = {table:Table2,quiz:ListChecks,flashcards:Layers,podcast:Headphones,slides:Presentation,mindmap:Network};
 return <section className="study-workspace" aria-label="Study Notebook" onKeyDown={event=>{if(event.key==='Escape'){const menu=(event.target as HTMLElement).closest<HTMLDetailsElement>('details.study-menu[open]');if(menu){event.stopPropagation();menu.removeAttribute('open');menu.querySelector<HTMLElement>('summary')?.focus();}}}} onClick={event=>{const target=event.target as HTMLElement;if(target.closest('button'))target.closest<HTMLDetailsElement>('details.study-menu')?.removeAttribute('open');}}>
  <div className="study-workspace__body" hidden={!library||advanced}><NotebookLibrary vaultPath={vaultPath} notebooks={collections} materials={allMaterials} onOpen={id=>{setSelected(id);setLibrary(false);}} onCreate={()=>void create()} onLegacy={()=>{setAdvanced(true);onOpenLegacy?.('workspace');}}/></div>
  <div className="study-workspace__body" hidden={library&&!advanced}>
  <header className="study-header"><div className="study-toolbar"><button onClick={()=>{setLibrary(true);setAdvanced(false);}}><ArrowLeft size={15}/> Back to notebooks</button><div className="study-heading"><span className="study-eyebrow">NOTEBOOK</span><select aria-label="Collection" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><button disabled={busy} onClick={()=>void create()}><Plus size={15}/> New notebook</button><details className="study-menu"><summary aria-label="Notebook actions"><MoreHorizontal size={18}/></summary><div className="study-menu-body"><button onClick={onImport}>Import content</button><button disabled={!active} onClick={()=>void run(async()=>{const title=await dialogs.prompt('Collection name',{initialValue:active?.title});if(title?.trim()&&active)await saveCollection(active.sourceIds,title.trim());})}>Rename collection</button><button onClick={()=>{setAdvanced(true);onOpenLegacy?.('workspace');}}>Advanced Notebook</button></div></details></div>{advanced&&<button onClick={()=>setAdvanced(false)}><ArrowLeft size={14}/> Back to study workspace</button>}{error&&<p role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button><button onClick={onOpenSettings}>AI settings</button></p>}</header>
  {advanced?<div className="flex-1 min-h-0">{legacy}</div>:<StudyPanels revealRevision={revealRevision} vaultPath={vaultPath} active={pane} onActive={setPane}
   sources={<div className="study-sources">
    {preview?<><div className="study-toolbar"><button onClick={()=>setPreview(null)}><ArrowLeft size={14}/> Sources</button><button disabled={preview.missing} onClick={()=>onOpenNote(preview.path)}>Open in Notes</button></div><h3>{preview.title}</h3><pre className="study-source-preview">{preview.missing?'This note is unavailable.':preview.text}</pre></>:<>
    <button className="study-add-source" disabled={!active} onClick={()=>setAdding(v=>!v)}><Plus size={16}/> {adding?'Done adding sources':'Add sources'}</button>
    {adding?<div className="study-source-picker"><label className="study-field">Find vault notes<input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}} placeholder="Search your vault…"/></label><button onClick={onImport}>Import content</button>{notes.map(note=><label className="study-source" key={note.id}><input type="checkbox" disabled={!active||busy} checked={active?.sourceIds.includes(note.id)??false} onChange={e=>{if(active)void run(()=>saveCollection(e.target.checked?[...active.sourceIds,note.id]:active.sourceIds.filter(id=>id!==note.id)));}}/><span>{note.title}<small>{note.path}</small></span></label>)}<div className="study-toolbar"><button disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-100))}>Previous</button><button disabled={next===null} onClick={()=>setOffset(next!)}>Next</button></div></div>:<>
    <p className="study-muted">{sources.length} selected source{sources.length===1?'':'s'}</p>
    {active?sources.length?sources.map((source,i)=><div className="study-source" key={source.id}><FileText size={17}/><button className="study-source-title" onClick={()=>void run(()=>previewSource(source.id))}>{source.title}<small title={source.path}>{source.path}</small>{source.missing&&<strong>Unavailable</strong>}{unsavedPaths.some(p=>p===source.path||p.endsWith('/'+source.path))&&<strong>Unsaved edits excluded</strong>}</button><details className="study-menu"><summary aria-label={`Actions for ${source.title}`}><MoreHorizontal size={16}/></summary><div className="study-menu-body"><button disabled={busy||i===0} onClick={()=>move(i,-1)}>Move up</button><button disabled={busy||i===sources.length-1} onClick={()=>move(i,1)}>Move down</button><button disabled={busy} onClick={()=>void run(()=>saveCollection(active.sourceIds.filter(id=>id!==source.id)))}>Remove source</button></div></details></div>):<div className="study-empty"><FileText size={28}/><h3>Add your first source</h3><p>Select saved notes from your vault to start learning.</p></div>:<div className="study-empty"><h3>Create a collection</h3><p>Bring your notes together in a notebook.</p></div>}
    </>}
    {!!newImports.length&&<div className="study-notice" role="status"><p>{newImports.length} imported notes are ready.</p><button disabled={busy||!active} onClick={()=>void run(async()=>{await saveCollection([...new Set([...(active?.sourceIds??[]),...newImports.map(n=>n.id)])]);setNewImports([]);})}>Add to collection</button><button onClick={()=>setNewImports([])}>Dismiss</button></div>}
    </>}
   </div>}
   chat={<><SharedChat onSources={()=>{setAdding(true);setPane('sources');setRevealRevision(r=>r+1);}} vaultPath={vaultPath} collectionId={selected||null} config={config} modelPicker={modelPicker} onVaultChanged={onVaultChanged} onOtherView={onOtherChatView} onOpenSettings={onOpenSettings}/>{shared.active&&shared.details[shared.active]?.collectionId!==selected&&selected&&<p className="study-scope-note">This conversation keeps its own sources until you choose “Use this collection”.</p>}</>}
   tools={<>{!!tasks.length&&<div className="study-task-status" aria-label="Tool activity">{tasks.map(task=>{const label=STUDY_TOOLS.find(t=>t.kind===task.kind)?.label??task.kind;const running=task.status==='preparing'||task.status==='generating';return <div key={task.id} className="study-task-row" data-status={task.status}><StatusMark progress={task.progress} status={TASK_STATUS[task.status]} label={task.status==='preparing'?`Preparing ${label}…`:task.status==='generating'?`Generating ${label}…`:task.status==='failed'?`${label} failed`:task.status==='cancelled'?`${label} cancelled`:label}/><span className="study-task-actions">{running&&<button onClick={()=>void cancelTask(task)}>Cancel</button>}{task.artifactId&&<button onClick={()=>{setSelected(task.collectionId);setLibrary(false);setPendingArtifact(task.artifactId!);}}>Open material</button>}{(task.status==='failed'||task.status==='cancelled')&&<button type="button" onClick={()=>void generate(task.kind,task.parentId,task.collectionId,task.instructions)}>Retry</button>}{!running&&<button type="button" aria-label={`Dismiss ${label} status`} onClick={()=>setTasks(rows=>rows.filter(t=>t.id!==task.id))}>Dismiss</button>}</span></div>;})}</div>}{detail?<><div className="study-viewer-back"><button onClick={()=>{setDetail(null);setArtifactByNotebook(rows=>({...rows,[selected]:''}));}}><ArrowLeft size={15}/> Tools</button></div></>:<div className="study-studio-home"><div className="study-tools">{STUDY_TOOLS.map(tool=>{const Icon=icons[tool.kind];return <button disabled={!canGenerate} key={tool.kind} onClick={()=>setConfigure(tool.kind)}><Icon size={20}/><span>{tool.label}</span></button>;})}</div>{!active?.sourceIds.length&&<p className="study-muted">Add sources to create study materials.</p>}

   <h3 className="study-list-heading">Saved materials <span>{artifacts.length}</span></h3><div className="study-material-list">{artifacts.map(a=>{const Icon=icons[a.kind];return <button className="study-material-row" key={a.id} onClick={()=>void run(()=>openArtifact(a.id))}><Icon size={22}/><span><strong>{a.title}</strong><small>{STUDY_TOOLS.find(t=>t.kind===a.kind)?.label} · {new Date(a.created*1000).toLocaleDateString()}{a.parentId?' · new version':''}</small></span></button>;})}{!artifacts.length&&<div className="study-empty"><Layers size={28}/><h3>Turn sources into understanding</h3><p>Your saved study materials will appear here.</p></div>}</div></div>}{Object.values(viewers).map(saved=><div className="study-workspace__body" hidden={detail?.artifact.id!==saved.artifact.id} key={saved.artifact.id}><ArtifactView vaultPath={vaultPath} detail={saved} onRefresh={async()=>{const updated=await study.request<ArtifactDetail>(vaultPath,'artifact',{id:saved.artifact.id});if(alive.current){setViewers(rows=>({...rows,[updated.artifact.id]:updated}));if(current.current===updated.artifact.collectionId){setDetail(updated);await refreshSelection();}}}} onRegenerate={()=>void generate(saved.artifact.kind,saved.artifact.id,saved.artifact.collectionId)} onSource={id=>void run(()=>previewSource(id))} onSetup={()=>{setAdvanced(true);onOpenLegacy?.('podcasts');}}/></div>)}</>}
  />}
  </div>
  <dialog ref={generationDialog} className="study-generation-dialog" onCancel={()=>setConfigure(null)}><form onSubmit={e=>{e.preventDefault();const kind=configure;setConfigure(null);if(kind)void generate(kind);}}><h2><SlidersHorizontal size={20}/> Create {STUDY_TOOLS.find(t=>t.kind===configure)?.label}</h2><p className="study-muted">Based on {sources.length} selected sources</p><label className="study-field">Optional instructions<textarea autoFocus value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Audience, topics, or learning goals…"/></label><div className="study-toolbar"><button type="button" onClick={()=>setConfigure(null)}>Cancel</button><button type="submit" disabled={!canGenerate}>Generate</button></div></form></dialog>
 </section>;
}
