import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { listen } from '@tauri-apps/api/event';
import { study, sharedStudy, useSharedStudy, STUDY_TOOLS, type Artifact, type ArtifactDetail, type Collection, type StudySource, type ToolKind } from '../../services/study';
import { useDialog } from '../DialogProvider';
import { SharedChat } from './SharedChat';
import { ArtifactView } from './ArtifactView';
import './study.css';

export function StudyWorkspace({vaultPath,onImport,onOpenNote,onOpenSettings,onOtherChatView,onOpenLegacy,legacy,unsavedPaths=[]}:{vaultPath:string;onImport:()=>void;onOpenNote:(path:string)=>void;onOpenSettings:()=>void;onOtherChatView:()=>void;onOpenLegacy?:(section:'workspace'|'transformations'|'podcasts'|'settings')=>void;legacy:ReactNode;unsavedPaths?:string[]}){
 const dialogs=useDialog();const shared=useSharedStudy(vaultPath);
 const [collections,setCollections]=useState<Collection[]>([]);const [selected,setSelected]=useState('');const [sources,setSources]=useState<StudySource[]>([]);const [notes,setNotes]=useState<StudySource[]>([]);const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [next,setNext]=useState<number|null>(null);const [pane,setPane]=useState('sources');const [advanced,setAdvanced]=useState(false);
 const [artifacts,setArtifacts]=useState<Artifact[]>([]);const [detail,setDetail]=useState<ArtifactDetail|null>(null);const [instructions,setInstructions]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [generating,setGenerating]=useState<ToolKind|null>(null);const [preview,setPreview]=useState<StudySource|null>(null);const [newImports,setNewImports]=useState<StudySource[]>([]);
 const alive=useRef(true);const current=useRef(selected);current.current=selected;const operation=useRef(0);const notesRevision=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;operation.current++;};},[]);
 const active=collections.find(c=>c.id===selected);
 const loadCollections=useCallback(async()=>{const rows=await study.request<Collection[]>(vaultPath,'collections');if(alive.current){setCollections(rows);setSelected(s=>s||rows[0]?.id||'');}},[vaultPath]);
 useEffect(()=>{void loadCollections().catch(e=>setError(String(e)));},[loadCollections]);
 const loadNotes=useCallback(async()=>{const revision=++notesRevision.current;const page=await study.request<{items:StudySource[];nextOffset:number|null}>(vaultPath,'notes',{query,offset});if(alive.current&&revision===notesRevision.current){setNotes(page.items);setNext(page.nextOffset);}},[vaultPath,query,offset]);
 useEffect(()=>{const timer=setTimeout(()=>void loadNotes().catch(e=>setError(String(e))),180);return()=>clearTimeout(timer);},[loadNotes]);
 const refreshSelection=useCallback(async()=>{if(!selected){setSources([]);setArtifacts([]);return;}const [sourceRows,materials]=await Promise.all([study.request<StudySource[]>(vaultPath,'sources',{collectionId:selected}),study.request<Artifact[]>(vaultPath,'artifacts',{collectionId:selected})]);if(alive.current&&current.current===selected){setSources(sourceRows);setArtifacts(materials);}},[vaultPath,selected]);
 useEffect(()=>{setDetail(null);setPreview(null);setNewImports([]);void refreshSelection().catch(e=>setError(String(e)));},[refreshSelection]);
 useEffect(()=>{const subscription=listen('knowledge-event',()=>{void loadNotes().catch(()=>{});void refreshSelection().catch(()=>{});if(detail)void openArtifact(detail.artifact.id).catch(()=>{});});return()=>{void subscription.then(stop=>stop()).catch(()=>{});};},[loadNotes,refreshSelection,detail?.artifact.id]);
 useEffect(()=>{const handler=(event:Event)=>{const {paths,vault}=(event as CustomEvent<{paths:string[];vault:string}>).detail;if(vault!==vaultPath||!current.current)return;void study.request<StudySource[]>(vaultPath,'importedPaths',{paths}).then(found=>{if(alive.current)setNewImports(found);}).catch(e=>{if(alive.current)setError(String(e));});};window.addEventListener('study-import-published',handler);return()=>window.removeEventListener('study-import-published',handler);},[vaultPath]);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setBusy(false);}};
 const saveCollection=async(sourceIds:string[],title=active?.title)=>{if(!active||!title)return;const row=await study.request<Collection>(vaultPath,'saveCollection',{...active,title,sourceIds});if(alive.current){setCollections(rows=>rows.map(c=>c.id===row.id?row:c));await refreshSelection();}};
 const create=()=>run(async()=>{const title=await dialogs.prompt('Collection name');if(!title?.trim())return;const row=await study.request<Collection>(vaultPath,'saveCollection',{title,sourceIds:[]});await loadCollections();setSelected(row.id);});
 const openArtifact=async(id:string)=>{const revision=++operation.current;const d=await study.request<ArtifactDetail>(vaultPath,'artifact',{id});if(alive.current&&revision===operation.current)setDetail(d);};
 const generate=async(kind:ToolKind,parentId:string|null=null)=>{if(!selected)return;const collectionId=selected;setGenerating(kind);setError('');try{const a=await study.generate(vaultPath,collectionId,kind,instructions,parentId);if(alive.current&&current.current===collectionId){await refreshSelection();await openArtifact(a.id);}}catch(e){if(alive.current)setError(String(e));}finally{if(alive.current)setGenerating(null);}};
 const previewSource=async(id:string)=>{const source=await study.request<StudySource>(vaultPath,'previewSource',{id});setPreview(source);setPane('sources');};
 const move=(index:number,delta:number)=>{if(!active)return;const ids=[...active.sourceIds];[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void run(()=>saveCollection(ids));};
 const canGenerate=!!active?.sourceIds.length&&!sources.some(s=>s.missing)&&!generating;
 if(!vaultPath)return <div className="study-workspace"><p>Open a vault to use Notebook.</p></div>;
 return <section className="study-workspace" aria-label="Study Notebook">
  <header className="study-header"><div className="study-toolbar"><h1>Notebook</h1><select aria-label="Collection" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select collection</option>{collections.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button disabled={busy} onClick={()=>void create()}>New collection</button><button onClick={onImport}>Import content</button><details><summary>Advanced</summary><button onClick={()=>{setAdvanced(true);onOpenLegacy?.('workspace');}}>Import directly to Notebook</button><button onClick={()=>{setAdvanced(true);onOpenLegacy?.('workspace');}}>Existing notebooks, notes, transformations and podcast settings</button></details></div><nav className="study-toolbar study-mobile-tabs" aria-label="Notebook areas">{['sources','chat','tools'].map(p=><button key={p} aria-pressed={pane===p} onClick={()=>setPane(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}</nav>{advanced&&<button onClick={()=>setAdvanced(false)}>Back to study workspace</button>}{error&&<p role="alert">{error}<button onClick={onOpenSettings}>AI settings</button></p>}{generating&&<p role="status">Generating {STUDY_TOOLS.find(t=>t.kind===generating)?.label}… You can change views. Progress and cancellation are available in Jobs.</p>}</header>
  {advanced?<div className="flex-1 min-h-0">{legacy}</div>:<div className="study-panes">
   <section className="study-pane" data-active={pane==='sources'} aria-label="Collection sources"><h2>Sources</h2><p className="study-muted">Live references to saved vault notes. Selecting a note does not copy or upload it.</p>{active?<><label className="study-field">Collection name<input key={active.id+active.revision} defaultValue={active.title} disabled={busy} onBlur={e=>{if(e.target.value.trim()&&e.target.value!==active.title)void run(()=>saveCollection(active.sourceIds,e.target.value));}}/></label><h3>Selected · {sources.length}</h3>{sources.map((source,i)=><div className="study-source" key={source.id}><label><button onClick={()=>void run(()=>previewSource(source.id))}>{source.title}</button><small>{source.path}</small>{source.missing&&<strong>Unavailable — remove or select a replacement</strong>}{unsavedPaths.some(p=>p===source.path||p.endsWith('/'+source.path))&&<strong>Unsaved edits excluded</strong>}</label><button aria-label={`Move ${source.title} up`} disabled={busy||i===0} onClick={()=>move(i,-1)}>↑</button><button aria-label={`Move ${source.title} down`} disabled={busy||i===sources.length-1} onClick={()=>move(i,1)}>↓</button><button aria-label={`Remove ${source.title}`} disabled={busy} onClick={()=>void run(()=>saveCollection(active.sourceIds.filter(id=>id!==source.id)))}>×</button></div>)}{!!newImports.length&&<div role="status"><p>{newImports.length} imported notes are ready.</p><button disabled={busy} onClick={()=>void run(async()=>{await saveCollection([...new Set([...active.sourceIds,...newImports.map(n=>n.id)])]);setNewImports([]);})}>Add imported notes to collection</button><button onClick={()=>setNewImports([])}>Dismiss</button></div>}</>:<p>Create a collection to select notes.</p>}<label className="study-field">Find vault notes<input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label>{notes.map(note=><div className="study-source" key={note.id}><label><input type="checkbox" disabled={!active||busy} checked={active?.sourceIds.includes(note.id)??false} onChange={e=>{if(active)void run(()=>saveCollection(e.target.checked?[...active.sourceIds,note.id]:active.sourceIds.filter(id=>id!==note.id)));}}/> {note.title}<small>{note.path}</small></label></div>)}<div className="study-toolbar"><button disabled={offset===0} onClick={()=>setOffset(o=>Math.max(0,o-100))}>Previous notes</button><button disabled={next===null} onClick={()=>setOffset(next!)}>Next notes</button></div>{preview&&<details open><summary>Saved note: {preview.title}</summary><pre className="study-prewrap">{preview.missing?'This note is unavailable.':preview.text}</pre><button disabled={preview.missing} onClick={()=>onOpenNote(preview.path)}>Open in Notes</button></details>}</section>
   <section className="study-pane" data-active={pane==='chat'} aria-label="Notebook chat"><SharedChat vaultPath={vaultPath} collectionId={selected||null} onOtherView={onOtherChatView} onOpenSettings={onOpenSettings}/>{shared.active&&shared.details[shared.active]?.collectionId!==selected&&selected&&<p className="study-muted">The current conversation keeps its own source selection until you choose “Use this collection”.</p>}</section>
   <section className="study-pane" data-active={pane==='tools'} aria-label="Study tools"><h2>Tools</h2><label className="study-field">Optional instructions<textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Audience, topics, or learning goals…"/></label><div className="study-tools">{STUDY_TOOLS.map(tool=><button disabled={!canGenerate} key={tool.kind} onClick={()=>void generate(tool.kind)}>{tool.label}</button>)}</div>{!active?.sourceIds.length&&<p>Select source notes to generate study material.</p>}<h3>Saved materials</h3><select aria-label="Saved material" value={detail?.artifact.id??''} onChange={e=>{if(e.target.value)void run(()=>openArtifact(e.target.value));}}><option value="">Choose saved material</option>{artifacts.map(a=><option key={a.id} value={a.id}>{a.title} · {STUDY_TOOLS.find(t=>t.kind===a.kind)?.label}{a.parentId?' · regenerated':''}</option>)}</select>{detail&&<ArtifactView key={detail.artifact.id} vaultPath={vaultPath} detail={detail} onRefresh={async()=>{await refreshSelection();await openArtifact(detail.artifact.id);}} onRegenerate={()=>void generate(detail.artifact.kind,detail.artifact.id)} onSource={id=>void run(()=>previewSource(id))} onSetup={()=>{setAdvanced(true);onOpenLegacy?.('podcasts');}}/>}</section>
  </div>}
 </section>;
}
