use super::*;
#[derive(Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct Artifact{pub id:String,pub collection_id:String,pub kind:String,pub title:String,pub version:i64,pub parent_id:Option<String>,pub snapshot_id:String,pub body:Value,pub created:i64}
fn row(r:&rusqlite::Row)->rusqlite::Result<Artifact>{let raw:String=r.get(7)?;Ok(Artifact{id:r.get(0)?,collection_id:r.get(1)?,kind:r.get(2)?,title:r.get(3)?,version:r.get(4)?,parent_id:r.get(5)?,snapshot_id:r.get(6)?,body:serde_json::from_str(&raw).map_err(|e|rusqlite::Error::FromSqlConversionFailure(7,rusqlite::types::Type::Text,Box::new(e)))?,created:r.get(8)?})}
pub fn get(c:&Connection,id:&str)->Result<Artifact,String>{c.query_row("SELECT * FROM artifacts WHERE id=?1",[id],row).map_err(error)}
pub fn list(c:&Connection,id:Option<&str>)->Result<Value,String>{let mut q=c.prepare("SELECT * FROM artifacts WHERE (?1 IS NULL OR collection_id=?1) ORDER BY created DESC,rowid DESC").map_err(error)?;let rows=q.query_map([id],row).map_err(error)?.collect::<Result<Vec<_>,_>>().map_err(error)?;Ok(json!(rows))}
pub fn insert(c:&Connection,collection:&str,kind:&str,mut body:Value,snapshot:&str,parent:Option<&str>)->Result<Artifact,String>{
    validate(kind,&body)?;
    if let Some(parent)=parent{let old=get(c,parent)?;if old.collection_id!=collection || old.kind!=kind{return Err("Regeneration must use the same collection and tool".into());}}
    // IDs belong to the application, not the language model.
    let key=match kind{"quiz"=>"questions","flashcards"=>"cards","slides"=>"slides","mindmap"=>"nodes",_=>"rows"};
    if let Some(rows)=body[key].as_array_mut(){for item in rows{if item.is_object() && kind!="mindmap"{item["id"]=json!(uuid::Uuid::new_v4().to_string());}}}
    if kind=="mindmap"{let original=body["nodes"].as_array().unwrap().clone();let ids:Vec<String>=original.iter().map(|_|uuid::Uuid::new_v4().to_string()).collect();let remap:std::collections::HashMap<String,String>=original.iter().zip(&ids).map(|(node,id)|(node["id"].as_str().unwrap().to_string(),id.clone())).collect();for (node,id) in body["nodes"].as_array_mut().unwrap().iter_mut().zip(ids){if let Some(parent)=node["parentId"].as_str().and_then(|old|remap.get(old)){node["parentId"]=json!(parent);}node["id"]=json!(id);}}
    let a=Artifact{id:uuid::Uuid::new_v4().to_string(),collection_id:collection.into(),kind:kind.into(),title:body["title"].as_str().unwrap_or(kind).chars().take(200).collect(),version:1,parent_id:parent.map(String::from),snapshot_id:snapshot.into(),body,created:now()};
    c.execute("INSERT INTO artifacts VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9)",params![a.id,a.collection_id,a.kind,a.title,a.version,a.parent_id,a.snapshot_id,a.body.to_string(),a.created]).map_err(error)?;Ok(a)
}
pub fn update(c:&Connection,old:&Artifact,next:&Artifact)->Result<(),String>{
    let tx=c.unchecked_transaction().map_err(error)?;
    if old.kind=="flashcards"{for card in next.body["cards"].as_array().unwrap(){let previous=old.body["cards"].as_array().unwrap().iter().find(|p|p["id"]==card["id"]);if previous.is_none_or(|p|p["front"]!=card["front"]||p["back"]!=card["back"]){tx.execute("DELETE FROM reviews WHERE artifact_id=?1 AND card_id=?2",params![next.id,card["id"].as_str()]).map_err(error)?;}}}
    tx.execute("UPDATE artifacts SET title=?2,version=?3,body=?4 WHERE id=?1",params![next.id,next.title,next.version,next.body.to_string()]).map_err(error)?;tx.commit().map_err(error)
}
pub fn parse(text:&str)->Result<Value,String>{let text=text.trim();let text=if text.starts_with("```"){text.lines().skip(1).collect::<Vec<_>>().join("\n").trim_end_matches('`').trim().to_string()}else{text.into()};serde_json::from_str(&text).map_err(|e|format!("Invalid generated structure: {e}. Retry explicitly."))}
fn array<'a>(v:&'a Value,key:&str)->Result<&'a Vec<Value>,String>{let a=v[key].as_array().ok_or_else(||format!("Missing {key} list"))?;if a.is_empty()||a.len()>500{return Err(format!("{key} must contain 1–500 items"));}Ok(a)}
fn text(v:&Value,key:&str)->Result<(),String>{if !v[key].as_str().is_some_and(|s|!s.trim().is_empty()&&s.len()<=50000){return Err(format!("Invalid {key}"));}Ok(())}
pub fn validate(kind:&str,v:&Value)->Result<(),String>{
    if v.to_string().len()>8*1024*1024{return Err("Artifact exceeds 8 MB".into());}text(v,"title")?;
    match kind{
        "table"=>{let cols=array(v,"columns")?;if cols.len()>20||cols.iter().any(|c|c.as_str().is_none()){return Err("Use up to 20 text columns".into());}for row in array(v,"rows")?{let cells=row["cells"].as_array().ok_or("Missing table cells")?;if cells.len()!=cols.len()||cells.iter().any(|v|!v.is_string()&&!v.is_null()){return Err("Table rows must match the columns".into());}}},
        "quiz"=>for q in array(v,"questions")?{text(q,"question")?;text(q,"explanation")?;let opts=array(q,"options")?;if !(2..=6).contains(&opts.len())||opts.iter().any(|x|!x.is_string())||q["answer"].as_u64().is_none_or(|n|n>=opts.len() as u64){return Err("Invalid quiz options or answer".into());}},
        "flashcards"=>for c in array(v,"cards")?{text(c,"front")?;text(c,"back")?;},
        "slides"=>for s in array(v,"slides")?{text(s,"title")?;if !s["bullets"].as_array().is_some_and(|a|a.len()<=12&&a.iter().all(Value::is_string))||!s["notes"].is_string(){return Err("Invalid slide bullets or speaker notes".into());}},
        "mindmap"=>{let nodes=array(v,"nodes")?;let mut ids=HashSet::new();for n in nodes{text(n,"id")?;text(n,"label")?;if !ids.insert(n["id"].as_str().unwrap()){return Err("Duplicate mind-map node".into());}}if nodes.iter().filter(|n|n["parentId"].is_null()).count()!=1{return Err("Mind map must have one root".into());}for n in nodes{let mut parent=&n["parentId"];let mut depth=1;while !parent.is_null(){let next=nodes.iter().find(|p|p["id"]==*parent).ok_or("Missing parent node")?;depth+=1;if depth>3{return Err("Mind map must be acyclic and at most three levels deep".into());}parent=&next["parentId"];}}},
        "podcast"=>{text(v,"transcript")?;},
        _=>return Err("Unknown study tool".into())
    }Ok(())
}
pub fn validate_sources(v:&Value,snap:&Snapshot)->Result<(),String>{
    fn walk(v:&Value,ids:&HashSet<&str>)->Result<(),String>{match v{Value::Object(o)=>{if let Some(sources)=o.get("sourceIds"){let a=sources.as_array().ok_or("Invalid source references")?;if a.iter().any(|id|id.as_str().is_none_or(|s|!ids.contains(s))){return Err("Generated material cites a source outside this selection".into());}}for value in o.values(){walk(value,ids)?;}},Value::Array(a)=>for value in a{walk(value,ids)?;},_=>()}Ok(())}
    walk(v,&snap.sources.iter().map(|s|s.id.as_str()).collect())
}
pub fn prompt(kind:&str)->Result<&'static str,String>{Ok(match kind{
"table"=>r#"Schema: {"title":"...","shortfall":"","columns":["..."],"rows":[{"cells":["..."],"sourceIds":["..."]}]}. Choose 4–8 useful columns. Unknown facts must be null; never invent data."#,
"quiz"=>r#"Schema: {"title":"...","shortfall":"","questions":[{"question":"...","options":["...","...","...","..."],"answer":0,"explanation":"...","sourceIds":["..."]}]}. Target 10 single-answer questions; answer is the zero-based correct option."#,
"flashcards"=>r#"Schema: {"title":"...","shortfall":"","cards":[{"front":"...","back":"...","sourceIds":["..."]}]}. Target 20 concise cards."#,
"slides"=>r#"Schema: {"title":"...","shortfall":"","slides":[{"title":"...","bullets":["..."],"notes":"Speaker notes","sourceIds":["..."]}]}. Target 10 slides, maximum 6 bullets each."#,
"mindmap"=>r#"Schema: {"title":"...","shortfall":"","nodes":[{"id":"root","parentId":null,"label":"...","sourceIds":["..."]},{"id":"child","parentId":"root","label":"...","sourceIds":["..."]}]}. One root, unique IDs, no cycles, at most 3 levels."#,
"podcast"=>r#"Schema: {"title":"...","shortfall":"","transcript":"A five-minute spoken script with speaker names","sourceIds":["..."]}. Write approximately 650 words, fewer if sources are insufficient. Audio will be generated separately with the user's existing podcast profiles."#,
_=>return Err("Unknown tool".into())})}
pub fn schedule(previous:i64,rating:&str,at:i64)->Result<(i64,i64),String>{let days=match rating{"again"=>0,"hard"=>1,"good"=>if previous==0{1}else{previous.saturating_mul(2).min(365)},"easy"=>if previous==0{4}else{previous.saturating_mul(3).min(365)},_=>return Err("Invalid review rating".into())};let due=if days==0{at.saturating_add(600)}else{at.saturating_add(days.saturating_mul(86400))};Ok((days,due))}
pub fn review(c:&Connection,id:&str,card:&str,rating:&str,at:i64)->Result<Value,String>{let a=get(c,id)?;if a.kind!="flashcards"||!a.body["cards"].as_array().unwrap().iter().any(|v|v["id"]==card){return Err("Card not found".into());}let old=c.query_row("SELECT interval_days FROM reviews WHERE artifact_id=?1 AND card_id=?2",params![id,card],|r|r.get(0)).optional().map_err(error)?.unwrap_or(0);let (interval,due)=schedule(old,rating,at)?;let tx=c.unchecked_transaction().map_err(error)?;tx.execute("INSERT INTO reviews VALUES(?1,?2,?3,?4) ON CONFLICT(artifact_id,card_id) DO UPDATE SET interval_days=excluded.interval_days,due=excluded.due",params![id,card,interval,due]).map_err(error)?;tx.execute("INSERT INTO review_events VALUES(?1,?2,?3,?4,?5,?6)",params![uuid::Uuid::new_v4().to_string(),id,card,rating,at,due]).map_err(error)?;tx.commit().map_err(error)?;reviews(c,id)}
pub fn reviews(c:&Connection,id:&str)->Result<Value,String>{let mut q=c.prepare("SELECT card_id,interval_days,due FROM reviews WHERE artifact_id=?1").map_err(error)?;let rows=q.query_map([id],|r|Ok(json!({"cardId":r.get::<_,String>(0)?,"intervalDays":r.get::<_,i64>(1)?,"due":r.get::<_,i64>(2)?}))).map_err(error)?.collect::<Result<Vec<_>,_>>().map_err(error)?;Ok(json!(rows))}
pub fn attempt(c:&Connection,id:&str,answers:Value)->Result<Value,String>{let a=get(c,id)?;if a.kind!="quiz"{return Err("Not a quiz".into());}let questions=a.body["questions"].as_array().unwrap();let answers=answers.as_array().ok_or("Invalid answers")?;if answers.len()!=questions.len(){return Err("Answer every question".into());}let mut score=0;for (q,answer) in questions.iter().zip(answers){let n=answer.as_u64().ok_or("Answer every question")?;if n>=q["options"].as_array().unwrap().len() as u64{return Err("Invalid choice".into());}if q["answer"].as_u64()==Some(n){score+=1;}}c.execute("INSERT INTO attempts VALUES(?1,?2,?3,?4,?5,?6)",params![uuid::Uuid::new_v4().to_string(),id,json!({"answers":answers,"artifactVersion":a.version}).to_string(),score,questions.len() as i64,now()]).map_err(error)?;attempts(c,id)}
pub fn attempts(c:&Connection,id:&str)->Result<Value,String>{let mut q=c.prepare("SELECT score,total,created FROM attempts WHERE artifact_id=?1 ORDER BY rowid DESC").map_err(error)?;let rows=q.query_map([id],|r|Ok(json!({"score":r.get::<_,i64>(0)?,"total":r.get::<_,i64>(1)?,"created":r.get::<_,i64>(2)?}))).map_err(error)?.collect::<Result<Vec<_>,_>>().map_err(error)?;Ok(json!(rows))}
#[cfg(test)]mod tests{use super::*;
#[test]fn scheduling_is_deterministic(){assert_eq!(schedule(0,"again",100).unwrap(),(0,700));assert_eq!(schedule(0,"good",100).unwrap(),(1,86500));assert_eq!(schedule(4,"good",0).unwrap().0,8);assert_eq!(schedule(0,"easy",0).unwrap().0,4);assert_eq!(schedule(200,"easy",0).unwrap().0,365);assert_eq!(schedule(100,"hard",0).unwrap().0,1);}
#[test]fn reject_invalid_quiz_and_cycles(){assert!(validate("quiz",&json!({"title":"Quiz","questions":[{"question":"q","explanation":"e","options":["a","b"],"answer":2}]})).is_err());assert!(validate("mindmap",&json!({"title":"Map","nodes":[{"id":"a","label":"a","parentId":"b"},{"id":"b","label":"b","parentId":"a"}]})).is_err());}
}
#[cfg(test)]mod persistence_tests{
 use super::*;
 #[test]fn reviews_attempts_and_card_edits_are_durable(){let c=Connection::open_in_memory().unwrap();super::super::migrate(&c).unwrap();let card=insert(&c,"c","flashcards",json!({"title":"Cards","cards":[{"front":"Q","back":"A","sourceIds":[]}]}),"snapshot",None).unwrap();let id=card.body["cards"][0]["id"].as_str().unwrap();review(&c,&card.id,id,"easy",1000).unwrap();assert_eq!(reviews(&c,&card.id).unwrap()[0]["due"],json!(1000+4*86400));let mut unchanged=card.clone();unchanged.version+=1;update(&c,&card,&unchanged).unwrap();assert_eq!(reviews(&c,&card.id).unwrap().as_array().unwrap().len(),1);let mut edited=unchanged.clone();edited.body["cards"][0]["back"]=json!("Changed");edited.version+=1;update(&c,&unchanged,&edited).unwrap();assert_eq!(reviews(&c,&card.id).unwrap(),json!([]));let events:i64=c.query_row("SELECT count(*) FROM review_events",[],|r|r.get(0)).unwrap();assert_eq!(events,1);let quiz=insert(&c,"c","quiz",json!({"title":"Quiz","questions":[{"question":"Q","options":["A","B"],"answer":1,"explanation":"Because","sourceIds":[]}]}),"s",None).unwrap();assert!(attempt(&c,&quiz.id,json!([null])).is_err());assert_eq!(attempt(&c,&quiz.id,json!([1])).unwrap()[0]["score"],1);let version=insert(&c,"c","flashcards",card.body.clone(),"new-snapshot",Some(&card.id)).unwrap();assert_ne!(version.id,card.id);assert!(reviews(&c,&version.id).unwrap().as_array().unwrap().is_empty());assert_eq!(get(&c,&card.id).unwrap().body["cards"][0]["back"],"Changed");}
 #[test]fn every_tool_has_a_valid_fixture(){let fixtures=vec![("table",json!({"title":"Table","columns":["A"],"rows":[{"cells":[null],"sourceIds":[]}]})),("quiz",json!({"title":"Quiz","questions":[{"question":"Q","options":["A","B"],"answer":0,"explanation":"A","sourceIds":[]}]})),("flashcards",json!({"title":"Cards","cards":[{"front":"Q","back":"A","sourceIds":[]}]})),("slides",json!({"title":"Slides","slides":[{"title":"Title","bullets":["Point"],"notes":"Notes","sourceIds":[]}]})),("mindmap",json!({"title":"Map","nodes":[{"id":"root","label":"Root","parentId":null,"sourceIds":[]}]})),("podcast",json!({"title":"Audio","transcript":"Transcript","sourceIds":[]}))];let c=Connection::open_in_memory().unwrap();super::super::migrate(&c).unwrap();for (kind,body)in fixtures{validate(kind,&body).unwrap();let a=insert(&c,"c",kind,body.clone(),"s",None).unwrap();assert_eq!(get(&c,&a.id).unwrap().kind,kind);if kind=="mindmap"{assert!(a.body["nodes"][0]["id"].as_str().unwrap().parse::<uuid::Uuid>().is_ok());}assert!(!prompt(kind).unwrap().is_empty());}}
}
