"""Generate TypeScript contracts from the verified pinned backend's OpenAPI."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schemas = json.loads((root / "notebook/openapi.json").read_text())["components"]["schemas"]


def ts(s):
    if "$ref" in s:
        return s["$ref"].split("/")[-1]
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in s["enum"])
    if "anyOf" in s:
        return " | ".join(ts(v) for v in s["anyOf"])
    kind = s.get("type")
    if kind == "array":
        return f"Array<{ts(s.get('items', {}))}>"
    if kind == "object":
        if "properties" in s:
            return "{ " + "; ".join(f'{json.dumps(k)}{"" if k in s.get("required", []) else "?"}: {ts(v)}' for k, v in s["properties"].items()) + " }"
        return "Record<string, " + (ts(s["additionalProperties"]) if isinstance(s.get("additionalProperties"), dict) else "unknown") + ">"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


(root / "src/types/notebook-api.ts").write_text("// Generated by scripts/generate-notebook-types.py; do not edit.\n" + "\n".join(f"export type {name} = {ts(s)};" for name, s in schemas.items()) + "\n")
